### ISSUE TITLE
Page break css rules not used?

### ISSUE THREAD

**Issue by IanWitham** [markdown-it/markdown-it#1103]
I've added some css rules to the moustache template head to try to tame the PDF page breaks:

```css
/* avoid breaking directly after a heading */
h1, h2, h3, h4, h5, h6 {
    break-after: avoid;
}

/* avoid breaking inside or before a codeblock.
(avoid breaking before because the preceding paragraph
probably adds context to the code block) */
pre {
    break-inside: avoid;
    break-before: avoid;
}

/* avoid breaking before or inside the last
paragraph in a section */
p + h1,
p + h2,
p + h3,
p + h4,
p + h5,
p + h6 {
    break-before: avoid;
    break-inside: avoid;
}
```

These are present in the HTML output, and Print Preview in Chrome does respect these rules.

However, they don't seem to have any effect in the output PDF. Is this normal? Is there a workaround?
