### ISSUE TITLE
Multi-line code blocks not recognizing new lines

### ISSUE THREAD

**Issue by zackhall** [markdown-it/markdown-it#214]
I have a code block that looks like such.

\`\`\`
var foo = "hello, world.";
console.log(foo);
\`\`\`

However, the output looks like: 

```
var foo = "hello, world."; console.log(foo);
```

This remains the same even if I put an extra newline in the code block. How can I enforce new lines in these code blocks?

**Comment by zackhall** [comment]
I've also tried to create a code block by adding 4 spaces in front of each line, but the same result.

**Comment by zackhall** [comment]
Hm, I realized I am using the gulp-markdown-it plugin which is quite out of date, though. Is there an up to date plugin for gulp?

**Comment by zackhall** [comment]
In case anyone comes across this and has similar questions:

It was not related to this plugin. It was related to the CSS of the website. 

The CSS was defined as: 

```css
code {
  white-space: nowrap;
}
```

Updating to this fixed everything up: 

```css
pre code {
  display: block;
}

code {
  white-space: pre;
}
```
