### ISSUE TITLE
Double dotted line on abbreviations

### ISSUE THREAD

**Issue by bjorn** [markdown-it/markdown-it#369]
On https://markdown-it.github.io/, abbreviations have a double dotted line on Chromium. This seems to be due to `type.less` and `bootstrap.css` doing:

```css
abbr[title] {
    border-bottom: 1px dotted;
}
```

Whereas my user agent stylesheet is doing:

```css
abbr[title], acronym[title] {
    text-decoration: underline dotted;
}
```

Those are different ways of putting a dotted line under the text and they appear in different positions. Actually, the position my browser uses by default looks better to me since it is closer to the text.

![2017-06-16-213854_3840x2160_scrot](https://user-images.githubusercontent.com/531764/27242193-4b75504a-52dc-11e7-8d81-4996e2e79594.png)
