### ISSUE TITLE
Token stream redesign

### ISSUE THREAD

**Issue by puzrin** [markdown-it/markdown-it#37]
Goals:

- unify renderers as much as possible
- simplify AST build
- unify attributes rendering

---

```yaml
token:
  type: link_open # ? may be "link", but that can make pairs scan more complex.
  tag: a

  # join as -1 | 0 | 1 ?
  single: false # true for pairs
  open: true # opening / closing tag

  map: [ line_begin, line_end ] # may be sometime [ line_begin, line_end, col_begin ]

  # only static things, with standard processing (html escape)
  # may be with boolean attrs
  # (?) complex things like multiple classes - now as single string, words separated by space
  attrs:
    - [ href, data ]
    - [ target, _blank ]
    - [ title, 'titke text' ]
    - [ alt, 'alt text' ]
    - [ id, '#...' ]

  markup: string # optional, describes used markup (bullet char, emphasis marker, hr markup)

  # self-closing tokens (fence, code)
  content: unparsed content
  fence_offset: 0
  info: ''

  # (?) link, image only (or via attributes?)
  destination: "http://..."

  # heading only
  heading_level: 3

  # paragraph only
  tight: false # true - member of tight list, should be hidden

  # inline container
  children: [...] # inline tags 
```

This ticket is for core devs only.
